### ISSUE TITLE
Show tooltip label in the right location

### ISSUE THREAD

**Issue by huyuwen** [ngLynx/ohmydash#22]
When mouse cursor moves to the yellow bubble, mouse cursor highlight the green bubble below according to X/Horizental axis location. The tooltips shows the green bubble data, but quite far away from the green bubble. This will confuse user which data has be highlighted.
![chrome_elmT1NK05p](https://user-images.githubusercontent.com/809513/90232327-cc85e900-de1c-11ea-9b87-d089b7777b74.png)

So 2 suggestions.
Alt1, Adjust tooltips selection reference, not only X Axis, but both X and Y Axix
Alt2, Show the tooltips close to the real highlight bubble.

**Comment by ngLynx** [comment]
fixed.
