### ISSUE TITLE
REST-API Data Simple Adapter

### ISSUE THREAD

**Issue by huyuwen** [ngLynx/ohmydash#25]
Currently, for rest-api data source, the response format must be 
```json
{
     "columns": ["column1", "column2", "column3"...],
     "rows": [
             ["column1-value1", "column2-value1", "column3-value1",...],
             ["column1-value2", "column2-value2", "column3-value2",...],
             ....      
     ]
}
```
This format couldn't match to most of the existing REST-API.
On simple adapter could be supported by define json-path mapping to column in REST-API Query JSON.
```json
{
    "method": "",
    "url": "",
    "headers": {
    "http-header-name": "http-header-value"
    },
    "body": {
    
    },
    "data-adapter": {
           "json-path1" : "column1",
           "json-path2" : "column2",
           .... 
    }
}
```
With this simple data adapter, user don't need to define additional code to mapping existing data response to the mandatory data format in ohmydash.

**Comment by ngLynx** [comment]
done! update the document, please give your comments.
